const thema2 = [
  { q: "1. Was ist eine Bewachung? (5P)", a: "Eine Bewachung ist der a) gewerbsmäßige b) Schutz von c) fremdem d) Eigentum oder e) Leben" },
  { q: "2. Nennen Sie die Voraussetzungen, die ein Gewerbetreibender erfüllen muss, damit ihm eine Bewachungserlaubnis erteilt werden kann. (6P)", a: "a) Mindestalter: 18 Jahre\nb) Zuverlässigkeit\nc) Mindestqualifikation: Sachkundeprüfung gem. §34a GewO\nd) Haftpflichtversicherung\ne) Wirtschaftlich geordnete Verhältnisse\nf) Liquiditätsreserve für Betriebskosten der ersten sechs Monate" },
  { q: "3. Welche Pflichten hat der Gewerbetreibende im Zusammenhang mit einer „Nachschau“? (2P)", a: "a) Er muss die Beauftragten der Gewerbebehörde unentgeltlich Auskünfte erteilen und\nb) ihnen die geschäftlichen Unterlagen und Belege vorzeigen" },
  { q: "4. Welche Stelle überprüft, ob ein Mitarbeiter im Sicherheitsgewerbe arbeiten darf oder nicht? (1P)", a: "Die zuständige Gewerbebehörde" },
  { q: "5. Welche Folgen kann ein Verstoß gegen die Gewerbeordnung haben? (2P)", a: "a) Rechtsfolgen von Verstößen nach dem Gewerberecht sind Geldbußen\nb) In einer Höhe bis zu 10.000 €" },
  { q: "6. Welche Qualifikation ist erforderlich um als Sicherheitsmitarbeiter zu arbeiten und folgende Tätigkeiten auszuüben: a) Pfortendienst in einem Chemiewerk, b) Geld- & Werttransport, c) Türsteher im gastgewerblichen Diskothekenbereich, d) Revierdienst mit Außenhautkontrollen, e) Personenschutz, f) Nachtwache in einem Museum (6P)", a: "a) Unterrichtung\nb) Unterrichtung\nc) Sachkundeprüfung\nd) Sachkundeprüfung (in der Regel finden hier auch Kontrollgänge im öffentlichen Raum statt)\ne) Unterrichtung\nf) Unterrichtung" },
  { q: "7. Kann man ein Sicherheitsgewerbe eröffnen, wenn man mehr als drei Kredite laufen hat, aber immer alle Raten pünktlich bezahlt? (1P)", a: "Ja, solange alle Kredite ordentlich bedient werden sind die wirtschaftlichen Verhältnisse weiterhin „geordnet“" },
  { q: "8. Nennen Sie beispielhaft drei Dokumente, die ein Bewachungsgewerbetreibender gemäß seiner Pflicht zur „Buchführung und Aufbewahrung“ im Rahmen einer Nachschau vorlegen muss. (3P)", a: "a) Vertrag der Haftpflichtversicherung\nb) Nachweise über Zuverlässigkeit und Befähigung von Wachpersonen\nc) Dienstanweisungen und Empfangsbestätigungen der Mitarbeiter\nd) Erklärungen zur Verschwiegenheitsverpflichtung der Mitarbeiter\ne) Vordruck des Dienstausweises\nf) Unterlagen zur Überprüfung und Freigabe waffenführender Mitarbeiter\ng) Anzeigen über Waffengebrauch" },
  { q: "9. Welche Mindestangaben muss ein Dienstausweis für Sicherheitsmitarbeiter enthalten? (7P)", a: "a) Name und Vorname der Wachperson\nb) Name und Anschrift des Gewerbetreibenden\nc) Falls abweichend Firmenname\nd) Bewacherregisteridentifikationsnummer der Wachperson\ne) Bewacherregisteridentifikationsnummer des Gewerbetreibenden\nf) Unterschrift der Wachperson\ng) Unterschrift des Gewerbetreibenden" },
  { q: "10. Bei welchen Tätigkeiten muss ein Sicherheitsmitarbeiter im Dienst ein Namens- oder Kennschild tragen und welche Angaben müssen darauf enthalten sein? (7P)", a: "a) Bei allen Tätigkeiten für die die Sachkundeprüfung gem. §34a GewO zwingend vorgeschrieben ist\nb) Außer: Kaufhausdetektive\nc) Bei allen Tätigkeiten in Flüchtlings- & Asylunterkünften\nd) Bei allen Tätigkeiten im Zusammenhang mit zugangsgeschützten Großveranstaltungen" },
  { q: "11. Welche Angaben muss die Dienstanweisung gemäß Bewachungsverordnung mindestens enthalten? (3P)", a: "a) Die Wachperson hat keine hoheitlichen Befugnisse\nb) Angabe ob und wenn ja welche Verteidigungswaffen im Dienst geführt werden sollen\nc) Wie nach einem Waffengebrauch zu verfahren ist" },
  { q: "12. Wo liegt der Unterschied zwischen der Unterrichtung und der Sachkundeprüfung gem. §34a GewO? (2P)", a: "a) Durch die Teilnahme am Unterrichtungsverfahren soll der Sicherheitsmitarbeiter mit seinen Rechten, Pflichten und Befugnissen vertraut gemacht werden\nb) Durch die Sachkundeprüfung soll der Nachweis erbracht werden, dass der Sicherheitsmitarbeiter seine Rechte, Pflichten und Befugnisse verinnerlicht hat" },
  { q: "13. Welche Anforderungen stellt die Bewachungsverordnung an die Dienstkleidung und Abzeichen von Sicherheitsmitarbeitern? (1P)", a: "Sie dürfen keine Verwechselungsgefahr zu Uniformen und Abzeichen von hoheitlichen Stellen bieten." },
  { q: "14. Wer ist von der Unterrichtung gem. §34a GewO befreit? Nennen Sie drei Beispiele! (3P)", a: "a) Wer bereits am 31.03.1996 im Bewachungsgewerbe tätig war\nb) Wer einen Abschluss als geprüfte Werkschutzfachkraft\nc) Geprüfte Schutz- und Sicherheitskraft\nd) Servicekraft für Schutz und Sicherheit\ne) Fachkraft für Schutz und Sicherheit\nf) Geprüfter Meister für Schutz und Sicherheit oder\ng) Geprüfter Werkschutzmeister nachweisen kann\nh) Wer die Laufbahnprüfung im mittleren Polizeivollzugsdienst, Justizvollzugsdienst oder bewaffneten Zolldienst nachweisen kann\ni) Wer ein rechtswissenschaftliches Studium abgeschlossen hat\nj) Wer die Sachkundeprüfung erfolgreich abgeschlossen hat" },
  { q: "15. Wer ist für die Aufbewahrung von Schusswaffen gemäß der Bewachungsverordnung verantwortlich? (1P)", a: "Ausschließlich der Gewerbetreibende" }
];

